# Use official Node.js Alpine image as base image
FROM node:22-alpine AS base

# Set the working directory in the container
WORKDIR /src

# Copy the package.json file to the working directory
COPY package*.json ./

# Install all the dependencies
RUN npm install

# Copy the content of the local directory to the working directory
COPY . .

# Start the app in development mode
CMD npm run dev