services:
  geomaticconnect-dev:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    env_file:
      - .env.local  
    container_name: geomaticconnect-dev
  geomaticconnect-prod:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    env_file:
      - .env
    container_name: geomaticconnect-prod