export const applicantsData = {
  data: [
    {
      _id: "1",
      fullName: "John Doe",
      email: "john.doe@example.com",
      state: "California",
      createdAt: "2023-10-01",
      role: "Junior Developer",
      stage: "Applied",
    },
    {
      _id: "2",
      fullName: "Sarah Johnson",
      email: "sarah.johnson@example.com",
      state: "Texas",
      createdAt: "2023-10-03",
      role: "UI/UX Designer",
      stage: "Interviewing",
    },
    {
      _id: "3",
      fullName: "Emily Davis",
      email: "emily.davis@example.com",
      state: "Florida",
      createdAt: "2023-10-06",
      role: "Product Manager",
      stage: "Rejected",
    },
    {
      _id: "4",
      fullName: "David Wilson",
      email: "david.wilson@example.com",
      state: "Washington",
      createdAt: "2023-10-07",
      role: "Data Analyst",
      stage: "Applied",
    },
  ],
  meta: {
    endCursor: false,
    hasNextPage: true,
    totalItems: 5,
  },
};
